### ISSUE TITLE
can't find c++ header

### ISSUE THREAD

**Issue by uwabami** [masa16/ruby-mathgl#1]
Hi,

```
    % ruby extconf.rb
    checking for mgl2/type.h... yes
    checking for mgl2/data.h... no
    *** extconf.rb failed ***
    ...
```

The "mgl2/data.h" contains the line "#include <vector>", this is a header file of C++, not C.

I don't know right way, but when I Add `with_cflags(" -x c++ ")` block, just fine.
Patch attached.

[0001-Check-C-header-Add-cflags-x-c.patch.gz](https://github.com/masa16/ruby-mathgl/files/160339/0001-Check-C-header-Add-cflags-x-c.patch.gz)

**Comment by uwabami** [comment]
Excuse me, I don't put my environment information.
- Distributor ID: Debian
- Description:    Debian GNU/Linux unstable (sid)
- Release:        unstable
- Codename:       sid
- Architecture: amd64 (x86_64
- ruby -v: ruby 2.3.0p0 (2015-12-25) [x86_64-linux-gnu]
- Mathgl: 2.3.4

Regards

**Comment by masa16** [comment]
It causes an error:
`
/tmp/ccb1alcG.o:(.eh_frame+0x12): undefined reference to `__gxx_personality_v0'
`
using gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC).
I modified that option:
`
with_cflags("-x c++ -lstdc++") do
`
then it is fine. Thank you.
